// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';

export function AddManualEntry(arg1:models.ManualEntryRequest):Promise<models.TimeEntry>;

export function DeleteEntry(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetDetectedBranches():Promise<Array<models.BranchDetection>>;

export function GetHistory():Promise<Array<models.TimeEntry>>;

export function GetHistoryFromClockify(arg1:string,arg2:string):Promise<Array<models.TimeEntry>>;

export function GetIntegrationStatus():Promise<models.IntegrationStatus>;

export function GetMyTickets():Promise<Array<models.JiraTicket>>;

export function GetProjects():Promise<Array<any>>;

export function GetTimerStatus():Promise<models.TimerState>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SearchTickets(arg1:string):Promise<Array<models.JiraTicket>>;

export function SetMockMode(arg1:string):Promise<void>;

export function StartTimer(arg1:string,arg2:string,arg3:string):Promise<models.TimerState>;

export function StopTimer():Promise<models.TimeEntry>;

export function UpdateEntry(arg1:models.UpdateEntryRequest):Promise<void>;
