// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {clockify} from '../models';
import {config} from '../models';

export function AddManualEntry(arg1:models.ManualEntryRequest):Promise<models.TimeEntry>;

export function ApplyUpdate(arg1:models.UpdateInfo):Promise<void>;

export function CheckForUpdates():Promise<models.UpdateInfo>;

export function CheckStartupUpdate():Promise<void>;

export function DeleteEntry(arg1:string):Promise<void>;

export function FetchWorkspaces(arg1:string):Promise<Array<clockify.WorkspaceInfo>>;

export function GetConfig():Promise<config.Config>;

export function GetConfigPath():Promise<string>;

export function GetDetectedBranches():Promise<Array<models.BranchDetection>>;

export function GetHistory():Promise<Array<models.TimeEntry>>;

export function GetHistoryFromClockify(arg1:string,arg2:string):Promise<Array<models.TimeEntry>>;

export function GetIntegrationStatus():Promise<models.IntegrationStatus>;

export function GetMyTickets():Promise<Array<models.JiraTicket>>;

export function GetProjects():Promise<Array<clockify.ProjectInfo>>;

export function GetTimerStatus():Promise<models.TimerState>;

export function GetUpdatePreferences():Promise<models.UpdatePreferences>;

export function GetVersion():Promise<string>;

export function InitTray(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SearchTickets(arg1:string):Promise<Array<models.JiraTicket>>;

export function SetMockMode(arg1:string):Promise<void>;

export function SetUpdatePreferences(arg1:models.UpdatePreferences):Promise<void>;

export function StartTimer(arg1:string,arg2:string,arg3:string):Promise<models.TimerState>;

export function StopTimer():Promise<models.TimeEntry>;

export function UpdateEntry(arg1:models.UpdateEntryRequest):Promise<void>;
