// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManualEntry(arg1) {
  return window['go']['app']['App']['AddManualEntry'](arg1);
}

export function ApplyUpdate(arg1) {
  return window['go']['app']['App']['ApplyUpdate'](arg1);
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function CheckStartupUpdate() {
  return window['go']['app']['App']['CheckStartupUpdate']();
}

export function DeleteEntry(arg1) {
  return window['go']['app']['App']['DeleteEntry'](arg1);
}

export function EnsureConfigPersisted() {
  return window['go']['app']['App']['EnsureConfigPersisted']();
}

export function FetchWorkspaces(arg1) {
  return window['go']['app']['App']['FetchWorkspaces'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['app']['App']['GetConfigPath']();
}

export function GetDetectedBranches() {
  return window['go']['app']['App']['GetDetectedBranches']();
}

export function GetHistory() {
  return window['go']['app']['App']['GetHistory']();
}

export function GetHistoryFromClockify(arg1, arg2) {
  return window['go']['app']['App']['GetHistoryFromClockify'](arg1, arg2);
}

export function GetIntegrationStatus() {
  return window['go']['app']['App']['GetIntegrationStatus']();
}

export function GetMyTickets() {
  return window['go']['app']['App']['GetMyTickets']();
}

export function GetProjects() {
  return window['go']['app']['App']['GetProjects']();
}

export function GetTimerStatus() {
  return window['go']['app']['App']['GetTimerStatus']();
}

export function GetUpdatePreferences() {
  return window['go']['app']['App']['GetUpdatePreferences']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function InitTray(arg1, arg2) {
  return window['go']['app']['App']['InitTray'](arg1, arg2);
}

export function RestartApplication() {
  return window['go']['app']['App']['RestartApplication']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SearchTickets(arg1) {
  return window['go']['app']['App']['SearchTickets'](arg1);
}

export function SetMockMode(arg1) {
  return window['go']['app']['App']['SetMockMode'](arg1);
}

export function SetUpdatePreferences(arg1) {
  return window['go']['app']['App']['SetUpdatePreferences'](arg1);
}

export function StartTimer(arg1, arg2, arg3) {
  return window['go']['app']['App']['StartTimer'](arg1, arg2, arg3);
}

export function StopTimer() {
  return window['go']['app']['App']['StopTimer']();
}

export function UpdateEntry(arg1) {
  return window['go']['app']['App']['UpdateEntry'](arg1);
}
