// Main application logic for Clockify ↔ Jira Time Sync
// Uses Wails Go bindings for all backend calls

import { formatDatetimeLocal, formatDuration, formatTime } from './utils/time.js';

// ===== Wails Bindings =====
// These are generated by Wails and available at runtime
const App = window.go?.app?.App ?? window.go?.internal?.app?.App;

// Wails runtime for events
let wailsRuntime;
try {
    wailsRuntime = window.runtime;
} catch (e) {
    // Will be available when running in Wails
}

// ===== State =====
let selectedTicket = null;
let timerInterval = null;
let timerStartTime = null;

// ===== Init =====
document.addEventListener('DOMContentLoaded', () => {
    initTheme();
    initTicketSearch();
    initTimer();
    initManualEntry();
    initHistory();
    initBranchDetection();
    initModal();
    initTabs();
    initModeToggle();
    initSettings();
    loadAssignedTickets();
    checkTimerStatus();
    setDefaultDates();
});

// ===== Theme =====
const systemDarkQuery = window.matchMedia('(prefers-color-scheme: dark)');

function getEffectiveTheme(pref) {
    if (pref === 'auto') return systemDarkQuery.matches ? 'dark' : 'light';
    return pref;
}

function applyTheme(pref) {
    const effective = getEffectiveTheme(pref);
    document.documentElement.setAttribute('data-theme', effective);
    updateThemeIcon(pref, effective);
}

function initTheme() {
    const saved = localStorage.getItem('theme-pref') || 'auto';
    applyTheme(saved);

    // Titlebar button cycles: auto → light → dark → auto
    document.getElementById('theme-toggle').addEventListener('click', () => {
        const current = localStorage.getItem('theme-pref') || 'auto';
        const cycle = { auto: 'light', light: 'dark', dark: 'auto' };
        const next = cycle[current] || 'auto';
        localStorage.setItem('theme-pref', next);
        applyTheme(next);
        // Sync settings dropdown if visible
        const sel = document.getElementById('theme-select');
        if (sel) sel.value = next;
    });

    // Settings dropdown
    const sel = document.getElementById('theme-select');
    if (sel) {
        sel.value = saved;
        sel.addEventListener('change', () => {
            const pref = sel.value;
            localStorage.setItem('theme-pref', pref);
            applyTheme(pref);
        });
    }

    // Listen for OS theme changes (only matters in auto mode)
    systemDarkQuery.addEventListener('change', () => {
        const pref = localStorage.getItem('theme-pref') || 'auto';
        if (pref === 'auto') applyTheme('auto');
    });
}

function updateThemeIcon(pref, effective) {
    const icon = document.querySelector('.theme-icon');
    if (!icon) return;
    const icons = { auto: '🖥', light: '☀️', dark: '🌙' };
    icon.textContent = icons[pref] || '🖥';
    const el = document.getElementById('theme-toggle');
    if (el) el.title = `Theme: ${pref} (${effective})`;
}

// ===== Ticket Search =====
let searchTimeout;

function initTicketSearch() {
    const input = document.getElementById('ticket-search');
    const dropdown = document.getElementById('search-results');

    input.addEventListener('input', (e) => {
        const query = e.target.value.trim();
        clearTimeout(searchTimeout);

        if (query.length < 2) {
            dropdown.classList.add('hidden');
            return;
        }

        searchTimeout = setTimeout(async () => {
            try {
                const tickets = await App.SearchTickets(query);
                renderDropdown(tickets, dropdown);
            } catch (err) {
                showToast('Search failed: ' + err, 'error');
            }
        }, 300); // debounce 300ms
    });

    // Show assigned tickets when focusing empty search
    input.addEventListener('focus', () => {
        if (!input.value.trim() && !selectedTicket) {
            document.getElementById('assigned-tickets').classList.remove('hidden');
        }
    });

    // Close dropdowns on outside click
    document.addEventListener('click', (e) => {
        if (!e.target.closest('.search-container') && !e.target.closest('#assigned-tickets')) {
            dropdown.classList.add('hidden');
            document.getElementById('assigned-tickets').classList.add('hidden');
        }
    });

    // Clear ticket button
    document.getElementById('clear-ticket-btn').addEventListener('click', clearTicket);

    // Toggle assigned tickets link
    const toggleAssignedBtn = document.getElementById('toggle-assigned-btn');
    if (toggleAssignedBtn) {
        toggleAssignedBtn.addEventListener('click', (e) => {
            e.preventDefault();
            const list = document.getElementById('assigned-tickets');
            if (list.classList.contains('hidden')) {
                list.classList.remove('hidden');
                toggleAssignedBtn.textContent = '❖ Hide tickets';
            } else {
                list.classList.add('hidden');
                toggleAssignedBtn.textContent = '❖ Show all my tickets';
            }
        });
    }
}

function renderDropdown(tickets, dropdown) {
    if (!tickets || tickets.length === 0) {
        dropdown.innerHTML = '<div class="dropdown-item"><span class="ticket-summary">No tickets found</span></div>';
        dropdown.classList.remove('hidden');
        return;
    }

    dropdown.innerHTML = tickets.map(t => `
        <div class="dropdown-item" data-key="${t.key}" data-summary="${escapeHtml(t.summary)}" data-status="${t.status}" data-type="${t.issueType}">
            <span class="ticket-key">${t.key}</span>
            <span class="ticket-summary">${escapeHtml(t.summary)}</span>
            <span class="ticket-type-badge">${t.issueType || 'Task'}</span>
        </div>
    `).join('');

    dropdown.querySelectorAll('.dropdown-item').forEach(item => {
        item.addEventListener('click', () => {
            selectTicket({
                key: item.dataset.key,
                summary: item.dataset.summary,
                status: item.dataset.status,
                issueType: item.dataset.type,
            });
            dropdown.classList.add('hidden');
            document.getElementById('ticket-search').value = '';
        });
    });

    dropdown.classList.remove('hidden');
}

function selectTicket(ticket) {
    selectedTicket = ticket;

    document.getElementById('selected-key').textContent = ticket.key;
    document.getElementById('selected-type').textContent = ticket.issueType || 'Task';
    document.getElementById('selected-summary').textContent = ticket.summary;
    document.getElementById('selected-status').textContent = ticket.status;
    document.getElementById('selected-ticket').classList.remove('hidden');

    document.getElementById('selected-type').classList.remove('hidden');
    document.getElementById('selected-status').classList.remove('hidden');

    document.getElementById('search-results').classList.add('hidden');
    document.getElementById('assigned-tickets').classList.add('hidden');
    document.querySelector('.search-container').classList.add('hidden');

    // Enable buttons
    document.getElementById('timer-start-btn').disabled = false;
    document.getElementById('manual-submit-btn').disabled = false;
}

function clearTicket() {
    selectedTicket = null;
    document.getElementById('selected-ticket').classList.add('hidden');
    document.querySelector('.search-container').classList.remove('hidden');
    document.getElementById('ticket-search').value = '';

    // Disable buttons
    document.getElementById('timer-start-btn').disabled = true;
    document.getElementById('manual-submit-btn').disabled = true;
}

async function loadAssignedTickets() {
    const container = document.getElementById('assigned-list');
    try {
        const tickets = await App.GetMyTickets();
        if (!tickets || tickets.length === 0) {
            container.innerHTML = '<div class="empty-state"><p>No assigned tickets found</p></div>';
            return;
        }

        container.innerHTML = tickets.map(t => `
            <div class="ticket-item" data-key="${t.key}" data-summary="${escapeHtml(t.summary)}" data-status="${t.status}" data-type="${t.issueType}">
                <span class="ticket-key">${t.key}</span>
                <span class="ticket-summary">${escapeHtml(t.summary)}</span>
            </div>
        `).join('');

        container.querySelectorAll('.ticket-item').forEach(item => {
            item.addEventListener('click', () => {
                selectTicket({
                    key: item.dataset.key,
                    summary: item.dataset.summary,
                    status: item.dataset.status,
                    issueType: item.dataset.type,
                });
                document.getElementById('assigned-tickets').classList.add('hidden');
                document.getElementById('toggle-assigned-btn').textContent = '❖ Show all my tickets';
            });
        });

        // Update count label if it exists
        const countLabel = document.getElementById('assigned-count');
        if (countLabel) {
            countLabel.textContent = `${tickets.length} open issues assigned to you`;
        }
    } catch (err) {
        container.innerHTML = `<div class="empty-state"><p>Failed to load tickets</p></div>`;
        console.error('Failed to load assigned tickets:', err);
    }
}

// ===== Timer =====
function initTimer() {
    document.getElementById('timer-start-btn').addEventListener('click', startTimer);
    document.getElementById('timer-stop-btn').addEventListener('click', stopTimer);
}

async function startTimer() {
    if (!selectedTicket) {
        showToast('Please select a ticket first', 'error');
        return;
    }

    try {
        const state = await App.StartTimer(selectedTicket.key);
        timerStartTime = new Date(state.startedAt);
        showTimerRunning(selectedTicket.key, selectedTicket.summary);
        showToast(`Timer started for ${selectedTicket.key}`, 'success');
    } catch (err) {
        showToast('Failed to start timer: ' + err, 'error');
    }
}

async function stopTimer() {
    try {
        const entry = await App.StopTimer();
        clearTimerUI();
        showToast(`Timer stopped — ${formatDuration(entry.duration)} logged`, 'success');
        refreshHistory();
    } catch (err) {
        showToast('Failed to stop timer: ' + err, 'error');
    }
}

function showTimerRunning(ticketKey, summary) {
    document.getElementById('timer-start-btn').classList.add('hidden');
    document.getElementById('timer-stop-btn').classList.remove('hidden');

    // In the new layout, we don't have a specific label for the ticket next to the timer, 
    // it's handled by the global ticket selector. We just update the status label.
    const statusLabel = document.getElementById('timer-status-label');
    if (statusLabel) statusLabel.textContent = 'RUNNING';

    document.getElementById('timer-display').classList.add('running');

    // Start live counter
    timerInterval = setInterval(() => {
        const elapsed = Math.floor((Date.now() - timerStartTime.getTime()) / 1000);
        document.getElementById('timer-display').textContent = formatTime(elapsed);
    }, 1000);
}

function clearTimerUI() {
    document.getElementById('timer-start-btn').classList.remove('hidden');
    document.getElementById('timer-stop-btn').classList.add('hidden');

    const statusLabel = document.getElementById('timer-status-label');
    if (statusLabel) statusLabel.textContent = 'IDLE';

    document.getElementById('timer-display').textContent = '00:00:00';
    document.getElementById('timer-display').classList.remove('running');

    if (timerInterval) {
        clearInterval(timerInterval);
        timerInterval = null;
    }
    timerStartTime = null;
}

async function checkTimerStatus() {
    try {
        const status = await App.GetTimerStatus();
        if (status && status.running) {
            timerStartTime = new Date(status.startedAt);
            selectedTicket = { key: status.ticketKey, summary: status.ticketSummary };
            showTimerRunning(status.ticketKey, status.ticketSummary);
        }
    } catch (err) {
        console.error('Failed to check timer status:', err);
    }
}

function initManualEntry() {
    document.getElementById('manual-submit-btn').addEventListener('click', async (e) => {
        e.preventDefault();

        if (!selectedTicket) {
            showToast('Please select a ticket first', 'error');
            return;
        }

        const req = {
            ticketKey: selectedTicket.key,
            date: document.getElementById('manual-date').value,
            startTime: document.getElementById('manual-start').value,
            endTime: document.getElementById('manual-end').value,
            description: document.getElementById('ticket-search').value.trim(),
        };

        if (!req.date || !req.startTime || !req.endTime) {
            showToast('Please fill in all time fields', 'error');
            return;
        }

        try {
            const entry = await App.AddManualEntry(req);
            showToast(`Entry added — ${formatDuration(entry.duration)}`, 'success');
            setDefaultDates();
            refreshHistory();
        } catch (err) {
            showToast('Failed to add entry: ' + err, 'error');
        }
    });
}

function setDefaultDates() {
    const today = new Date().toISOString().split('T')[0];
    document.getElementById('manual-date').value = today;

    // History date range: last 7 days
    const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
    document.getElementById('history-start').value = weekAgo;
    document.getElementById('history-end').value = today;
}

// ===== History =====
function initHistory() {
    document.getElementById('history-fetch-btn').addEventListener('click', fetchHistoryFromClockify);
    refreshHistory();
}

async function refreshHistory() {
    try {
        const entries = await App.GetHistory();
        renderHistory(entries);
    } catch (err) {
        console.error('Failed to refresh history:', err);
    }
}

async function fetchHistoryFromClockify() {
    const start = document.getElementById('history-start').value;
    const end = document.getElementById('history-end').value;

    if (!start || !end) {
        showToast('Please select a date range', 'error');
        return;
    }

    try {
        const entries = await App.GetHistoryFromClockify(start, end);
        renderHistory(entries);
        showToast(`Fetched ${entries?.length || 0} entries from Clockify`, 'info');
    } catch (err) {
        showToast('Failed to fetch history: ' + err, 'error');
    }
}

function renderHistory(entries) {
    const container = document.getElementById('history-list');

    if (!entries || entries.length === 0) {
        container.innerHTML = `
            <div class="empty-state">
                <span class="empty-icon">📭</span>
                <p>No entries yet. Start a timer or add a manual entry.</p>
            </div>
        `;
        return;
    }

    container.innerHTML = entries.map(e => {
        const startStr = new Date(e.start).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
        const endStr = e.end ? new Date(e.end).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—';
        const dateStr = new Date(e.start).toLocaleDateString([], { month: 'short', day: 'numeric' });

        return `
            <div class="history-entry" data-id="${e.id}">
                <span class="entry-ticket">${e.ticketKey || '—'}</span>
                <div class="entry-details">
                    <span class="entry-description">${escapeHtml(e.ticketSummary || e.description || '')}</span>
                    <span class="entry-time">${dateStr} · ${startStr} → ${endStr}</span>
                </div>
                <span class="entry-duration">${formatDuration(e.duration)}</span>
                <div class="entry-actions">
                    <button class="icon-btn edit-btn" title="Edit" data-entry='${JSON.stringify(e).replace(/'/g, "&#39;")}'>✏️</button>
                    <button class="icon-btn delete-btn" title="Delete" data-id="${e.id}">🗑️</button>
                </div>
            </div>
        `;
    }).join('');

    // Edit buttons
    container.querySelectorAll('.edit-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            const entry = JSON.parse(btn.dataset.entry);
            openEditModal(entry);
        });
    });

    // Delete buttons
    container.querySelectorAll('.delete-btn').forEach(btn => {
        btn.addEventListener('click', async () => {
            const id = btn.dataset.id;
            if (confirm('Delete this time entry?')) {
                try {
                    await App.DeleteEntry(id);
                    showToast('Entry deleted', 'success');
                    refreshHistory();
                } catch (err) {
                    showToast('Failed to delete: ' + err, 'error');
                }
            }
        });
    });
}

// ===== Edit Modal =====
function initModal() {
    document.getElementById('edit-cancel-btn').addEventListener('click', closeEditModal);
    document.querySelector('.modal-backdrop')?.addEventListener('click', closeEditModal);

    document.getElementById('edit-form').addEventListener('submit', async (e) => {
        e.preventDefault();

        const req = {
            id: document.getElementById('edit-id').value,
            ticketKey: document.getElementById('edit-ticket').value.trim(),
            start: new Date(document.getElementById('edit-start').value).toISOString(),
            end: new Date(document.getElementById('edit-end').value).toISOString(),
            description: document.getElementById('edit-description').value.trim(),
        };

        try {
            await App.UpdateEntry(req);
            showToast('Entry updated', 'success');
            closeEditModal();
            refreshHistory();
        } catch (err) {
            showToast('Failed to update: ' + err, 'error');
        }
    });
}

function openEditModal(entry) {
    document.getElementById('edit-id').value = entry.id;
    document.getElementById('edit-ticket').value = entry.ticketKey || '';
    document.getElementById('edit-description').value = entry.description || entry.ticketSummary || '';

    // Format for datetime-local input
    if (entry.start) {
        const start = new Date(entry.start);
        document.getElementById('edit-start').value = formatDatetimeLocal(start);
    }
    if (entry.end) {
        const end = new Date(entry.end);
        document.getElementById('edit-end').value = formatDatetimeLocal(end);
    }

    document.getElementById('edit-modal').classList.remove('hidden');
}

function closeEditModal() {
    document.getElementById('edit-modal').classList.add('hidden');
}

// ===== Branch Detection (SSE via Wails Events) =====
function initBranchDetection() {
    // Listen for Wails runtime events
    if (window.runtime) {
        window.runtime.EventsOn('branch-detected', (detection) => {
            showBranchBanner(detection);
        });
    }
}

function showBranchBanner(detection) {
    const banner = document.getElementById('branch-banner');
    document.getElementById('branch-ticket-key').textContent = detection.ticketKey;
    document.getElementById('branch-name').textContent = detection.branchName;
    document.getElementById('branch-ide').textContent = detection.ide;
    banner.classList.remove('hidden');

    // Track button
    document.getElementById('branch-track-btn').onclick = () => {
        selectTicket({
            key: detection.ticketKey,
            summary: '',
            status: '',
            issueType: '',
        });
        // Auto-start timer
        startTimer();
        banner.classList.add('hidden');
    };

    // Dismiss button
    document.getElementById('branch-dismiss-btn').onclick = () => {
        banner.classList.add('hidden');
    };
}

// ===== Toasts =====
function showToast(message, type = 'info') {
    const container = document.getElementById('toast-container');
    const icons = { success: '✅', error: '❌', info: 'ℹ️' };

    const toast = document.createElement('div');
    toast.className = `toast ${type}`;
    toast.innerHTML = `
        <span class="toast-icon">${icons[type] || icons.info}</span>
        <span>${escapeHtml(message)}</span>
    `;

    container.appendChild(toast);

    setTimeout(() => {
        toast.style.opacity = '0';
        toast.style.transform = 'translateX(20px)';
        toast.style.transition = 'all 0.3s ease';
        setTimeout(() => toast.remove(), 300);
    }, 4000);
}

// ===== Tabs =====
function initTabs() {
    const btns = document.querySelectorAll('.nav-tab');
    const panels = document.querySelectorAll('.main-view');

    btns.forEach(btn => {
        btn.addEventListener('click', () => {
            btns.forEach(b => b.classList.remove('active'));
            panels.forEach(p => {
                p.classList.remove('active');
                p.classList.add('hidden');
                p.style.display = 'none';
            });

            btn.classList.add('active');
            const target = document.getElementById(btn.dataset.target);
            target.classList.remove('hidden');
            target.classList.add('active');
            target.style.display = 'flex'; // Ensure flex layout for main-view
        });
    });
}

// ===== Mode Toggle (Timer vs Manual) =====
function initModeToggle() {
    const timerBtn = document.getElementById('mode-timer-btn');
    const manualBtn = document.getElementById('mode-manual-btn');

    // Containers
    const timerDisplay = document.getElementById('timer-display-container');
    const manualDisplay = document.getElementById('manual-display-container');

    // Action Buttons
    const startTrackerBtn = document.getElementById('timer-start-btn');
    const addManualBtn = document.getElementById('manual-submit-btn');

    timerBtn.addEventListener('click', () => {
        timerBtn.classList.replace('btn-ghost', 'btn-secondary');
        manualBtn.classList.replace('btn-secondary', 'btn-ghost');

        timerDisplay.classList.remove('hidden');
        manualDisplay.classList.add('hidden');

        startTrackerBtn.classList.remove('hidden');
        addManualBtn.classList.add('hidden');
    });

    manualBtn.addEventListener('click', () => {
        manualBtn.classList.replace('btn-ghost', 'btn-secondary');
        timerBtn.classList.replace('btn-secondary', 'btn-ghost');

        manualDisplay.classList.remove('hidden');
        timerDisplay.classList.add('hidden');

        addManualBtn.classList.remove('hidden');
        startTrackerBtn.classList.add('hidden');
    });
}

// ===== Settings =====

async function fetchAndPopulateWorkspaces(apiKey, selectedId) {
    const ws = document.getElementById('setting-clockify-ws');
    ws.innerHTML = '<option value="">Loading…</option>';
    try {
        const workspaces = await App.FetchWorkspaces(apiKey);
        ws.innerHTML = '';
        if (!workspaces || workspaces.length === 0) {
            ws.innerHTML = '<option value="">No workspaces found</option>';
            return;
        }
        for (const w of workspaces) {
            const opt = document.createElement('option');
            opt.value = w.id;
            opt.textContent = w.name;
            ws.appendChild(opt);
        }
        // Auto-select: saved value, or the only workspace
        if (selectedId && [...ws.options].some(o => o.value === selectedId)) {
            ws.value = selectedId;
        } else if (workspaces.length === 1) {
            ws.value = workspaces[0].id;
        }
    } catch (err) {
        ws.innerHTML = '<option value="">Failed to load workspaces</option>';
        console.error('Failed to fetch workspaces:', err);
    }
}

function initSettings() {
    // Display app version
    if (App.GetVersion) {
        App.GetVersion().then(v => {
            const el = document.getElementById('app-version');
            if (el) el.textContent = `clockify-jira-sync v${v}`;
        }).catch(() => {});
    }

    // Populate form if backend supports getting config
    if (App.GetConfig) {
        App.GetConfig().then(cfg => {
            if (cfg) {
                document.getElementById('setting-clockify-key').value = cfg.ClockifyAPIKey || '';
                document.getElementById('setting-jira-url').value = cfg.JiraBaseURL || '';
                document.getElementById('setting-jira-email').value = cfg.JiraEmail || '';
                document.getElementById('setting-jira-token').value = cfg.JiraAPIToken || '';

                // Load workspaces if API key is present
                if (cfg.ClockifyAPIKey) {
                    fetchAndPopulateWorkspaces(cfg.ClockifyAPIKey, cfg.ClockifyWorkspace);
                } else {
                    const ws = document.getElementById('setting-clockify-ws');
                    ws.innerHTML = '<option value="">— enter API key to load —</option>';
                }
            }
        }).catch(err => {
            console.error("Could not load config:", err);
        }).finally(() => {
            refreshIntegrationStatus();
        });
    } else {
        refreshIntegrationStatus();
    }

    // Auto-fetch workspaces when API key changes
    document.getElementById('setting-clockify-key').addEventListener('blur', () => {
        const apiKey = document.getElementById('setting-clockify-key').value.trim();
        if (apiKey) {
            fetchAndPopulateWorkspaces(apiKey, '');
        } else {
            const ws = document.getElementById('setting-clockify-ws');
            ws.innerHTML = '<option value="">— enter API key to load —</option>';
        }
    });

    document.getElementById('settings-api-form').addEventListener('submit', async (e) => {
        e.preventDefault();

        const wsVal = document.getElementById('setting-clockify-ws').value.trim();
        const config = {
            ClockifyAPIKey: document.getElementById('setting-clockify-key').value.trim(),
            ClockifyWorkspace: (wsVal && wsVal !== 'undefined') ? wsVal : '',
            JiraBaseURL: document.getElementById('setting-jira-url').value.trim(),
            JiraEmail: document.getElementById('setting-jira-email').value.trim(),
            JiraAPIToken: document.getElementById('setting-jira-token').value.trim(),
        };

        try {
            if (App.SaveConfig) {
                await App.SaveConfig(config);
                showToast('Settings saved successfully', 'success');
            } else {
                showToast('SaveConfig not implemented in backend yet', 'info');
            }
        } catch (err) {
            showToast('Failed to save settings: ' + (err?.message || err), 'error');
        } finally {
            await refreshIntegrationStatus();
        }
    });
}

function setIntegrationBadge(elementId, state, message = '') {
    const badge = document.getElementById(elementId);
    if (!badge) return;

    if (state === 'connected') {
        badge.textContent = 'Connected';
        badge.style.background = 'rgba(34, 197, 94, 0.15)';
        badge.style.color = 'var(--success)';
    } else if (state === 'disconnected') {
        badge.textContent = 'Disconnected';
        badge.style.background = 'rgba(239, 68, 68, 0.15)';
        badge.style.color = 'var(--danger)';
    } else {
        badge.textContent = 'Checking...';
        badge.style.background = 'rgba(156, 163, 175, 0.2)';
        badge.style.color = 'var(--text-secondary)';
    }

    if (message) {
        badge.title = message;
    } else {
        badge.removeAttribute('title');
    }
}

async function refreshIntegrationStatus() {
    setIntegrationBadge('status-clockify', 'checking');
    setIntegrationBadge('status-jira', 'checking');

    if (!App.GetIntegrationStatus) {
        const msg = 'Status checks are not available in this backend build.';
        setIntegrationBadge('status-clockify', 'disconnected', msg);
        setIntegrationBadge('status-jira', 'disconnected', msg);
        return;
    }

    try {
        const status = await App.GetIntegrationStatus();
        setIntegrationBadge(
            'status-clockify',
            status.clockifyConnected ? 'connected' : 'disconnected',
            status.clockifyError || ''
        );
        setIntegrationBadge(
            'status-jira',
            status.jiraConnected ? 'connected' : 'disconnected',
            status.jiraError || ''
        );
    } catch (err) {
        const msg = err?.message || String(err);
        setIntegrationBadge('status-clockify', 'disconnected', msg);
        setIntegrationBadge('status-jira', 'disconnected', msg);
    }
}

// ===== Utility Functions =====
function escapeHtml(str) {
    if (!str) return '';
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
}
