// Main application logic for JiraFy Clockwork
// Uses Wails Go bindings for all backend calls

import { formatDatetimeLocal, formatDuration, formatTime } from './utils/time.js';
import { normalizeLogRoundingMin, normalizeSummaryWordLimit } from './utils/settings.js';

// ===== Wails Bindings =====
// These are generated by Wails and available at runtime
const App = window.go?.app?.App ?? window.go?.internal?.app?.App;

// Wails runtime for events
let wailsRuntime;
try {
    wailsRuntime = window.runtime;
} catch (e) {
    // Will be available when running in Wails
}

// ===== State =====
let selectedTicket = null;
let timerInterval = null;
let timerStartTime = null;
let traySelectedTicket = null;
let traySearchTimeout = null;
let summaryWordLimit = 0;

// ===== Init =====
document.addEventListener('DOMContentLoaded', () => {
    initTheme();
    initTicketSearch();
    initTimer();
    initManualEntry();
    initHistory();
    initBranchDetection();
    initModal();
    initTrayStartTimerModal();
    initTabs();
    initModeToggle();
    initSettings();
    loadAssignedTickets();
    loadProjects();
    checkTimerStatus();
    setDefaultDates();
});

// ===== Theme =====
const systemDarkQuery = window.matchMedia('(prefers-color-scheme: dark)');

function getEffectiveTheme(pref) {
    if (pref === 'auto') return systemDarkQuery.matches ? 'dark' : 'light';
    return pref;
}

function applyTheme(pref) {
    const effective = getEffectiveTheme(pref);
    document.documentElement.setAttribute('data-theme', effective);
    updateThemeIcon(pref, effective);
}

function initTheme() {
    const saved = localStorage.getItem('theme-pref') || 'auto';
    applyTheme(saved);

    // Titlebar button cycles: auto → light → dark → auto
    document.getElementById('theme-toggle').addEventListener('click', () => {
        const current = localStorage.getItem('theme-pref') || 'auto';
        const cycle = { auto: 'light', light: 'dark', dark: 'auto' };
        const next = cycle[current] || 'auto';
        localStorage.setItem('theme-pref', next);
        applyTheme(next);
        // Sync settings dropdown if visible
        const sel = document.getElementById('theme-select');
        if (sel) sel.value = next;
    });

    // Settings dropdown
    const sel = document.getElementById('theme-select');
    if (sel) {
        sel.value = saved;
        sel.addEventListener('change', () => {
            const pref = sel.value;
            localStorage.setItem('theme-pref', pref);
            applyTheme(pref);
        });
    }

    // Listen for OS theme changes (only matters in auto mode)
    systemDarkQuery.addEventListener('change', () => {
        const pref = localStorage.getItem('theme-pref') || 'auto';
        if (pref === 'auto') applyTheme('auto');
    });
}

function updateThemeIcon(pref, effective) {
    const icon = document.querySelector('.theme-icon');
    if (!icon) return;
    const icons = { auto: '🖥', light: '☀️', dark: '🌙' };
    icon.textContent = icons[pref] || '🖥';
    const el = document.getElementById('theme-toggle');
    if (el) el.title = `Theme: ${pref} (${effective})`;
}

// ===== Ticket Search =====
let searchTimeout;
let assignedTickets = []; // cached assigned tickets for focus dropdown

function initTicketSearch() {
    const input = document.getElementById('ticket-search');
    const dropdown = document.getElementById('search-results');

    // Regex matching a full Jira key followed by a space: "PROJ-123 ..."
    const fullKeyWithSpace = /^([A-Z][A-Z0-9]+-\d+)\s/i;

    input.addEventListener('input', (e) => {
        clearTimeout(searchTimeout);
        const query = input.value.trim();

        if (query.length === 0) {
            selectedTicket = null;
            document.getElementById('clear-ticket-btn').classList.add('hidden');
            document.getElementById('timer-start-btn').disabled = true;
            document.getElementById('manual-submit-btn').disabled = true;
            renderAssignedDropdown(dropdown);
            return;
        }

        // If a ticket is selected and input has the key followed by a space,
        // the user is editing the description — don't search
        if (selectedTicket && query.toUpperCase().startsWith(selectedTicket.key.toUpperCase() + ' ')) {
            dropdown.classList.add('hidden');
            return;
        }

        // If no ticket selected but input matches "KEY-123 ...", auto-lock
        // the ticket so the user can type a description without triggering search
        if (!selectedTicket) {
            const keyMatch = input.value.match(fullKeyWithSpace);
            if (keyMatch) {
                const typedKey = keyMatch[1].toUpperCase();
                // Look in cached assigned tickets first
                const found = assignedTickets.find(t => t.key.toUpperCase() === typedKey);
                if (found) {
                    selectedTicket = found;
                } else {
                    // Create a minimal ticket object from the typed key
                    selectedTicket = { key: typedKey, summary: '', status: '', issueType: '' };
                }
                document.getElementById('clear-ticket-btn').classList.remove('hidden');
                document.getElementById('timer-start-btn').disabled = false;
                document.getElementById('manual-submit-btn').disabled = false;
                dropdown.classList.add('hidden');
                return;
            }
        }

        // If the selected ticket's key no longer matches, clear the selection
        if (selectedTicket) {
            selectedTicket = null;
            document.getElementById('timer-start-btn').disabled = true;
            document.getElementById('manual-submit-btn').disabled = true;
        }

        // For 1-char queries, show local matches immediately then also query Jira
        if (query.length === 1) {
            const filtered = assignedTickets.filter(t =>
                t.key.toUpperCase().startsWith(query.toUpperCase()) ||
                t.summary.toUpperCase().startsWith(query.toUpperCase())
            );
            if (filtered.length > 0) {
                renderDropdown(filtered, dropdown);
            }
        }

        // Query Jira for all queries (debounced)
        searchTimeout = setTimeout(async () => {
            try {
                const tickets = await App.SearchTickets(query);
                renderDropdown(tickets, dropdown);
            } catch (err) {
                showToast('Search failed: ' + err, 'error');
            }
        }, 300);
    });

    // Show assigned tickets when focusing empty search
    input.addEventListener('focus', () => {
        if (input.value.trim().length < 2) {
            renderAssignedDropdown(dropdown);
        }
    });

    // Close dropdown on outside click
    document.addEventListener('click', (e) => {
        if (!e.target.closest('.search-container')) {
            dropdown.classList.add('hidden');
        }
    });

    // Clear ticket button
    document.getElementById('clear-ticket-btn').addEventListener('click', () => clearTicket());
}

function renderAssignedDropdown(dropdown) {
    if (!assignedTickets || assignedTickets.length === 0) {
        dropdown.classList.add('hidden');
        return;
    }
    renderDropdown(assignedTickets, dropdown);
}

function renderDropdown(tickets, dropdown) {
    if (!tickets || tickets.length === 0) {
        dropdown.innerHTML = '<div class="dropdown-item"><span class="ticket-summary">No tickets found</span></div>';
        dropdown.classList.remove('hidden');
        return;
    }

    // Limit to 5 results in the dropdown
    const shown = tickets.slice(0, 5);

    dropdown.innerHTML = shown.map(t => {
        const fullSummary = String(t.summary || '').trim();
        const escapedFullSummary = escapeHtml(fullSummary);
        return `
        <div class="dropdown-item" data-key="${t.key}" data-summary="${escapedFullSummary}" data-status="${t.status}" data-type="${t.issueType}">
            <span class="ticket-key">${t.key}</span>
            <span class="ticket-summary" title="${escapedFullSummary}">${escapedFullSummary}</span>
            <span class="ticket-type-badge">${t.issueType || 'Task'}</span>
        </div>
    `;
    }).join('');

    dropdown.querySelectorAll('.dropdown-item').forEach(item => {
        item.addEventListener('click', () => {
            selectTicket({
                key: item.dataset.key,
                summary: item.dataset.summary,
                status: item.dataset.status,
                issueType: item.dataset.type,
            });
        });
    });

    dropdown.classList.remove('hidden');
}

function selectTicket(ticket) {
    selectedTicket = ticket;

    const input = document.getElementById('ticket-search');
    const clearBtn = document.getElementById('clear-ticket-btn');

    // Show key + summary as plain editable text
    input.value = ticket.key + ' ' + ticket.summary;
    clearBtn.classList.remove('hidden');

    // Hide dropdown
    document.getElementById('search-results').classList.add('hidden');

    // Enable buttons
    document.getElementById('timer-start-btn').disabled = false;
    document.getElementById('manual-submit-btn').disabled = false;
}

function clearTicket() {
    selectedTicket = null;

    const clearBtn = document.getElementById('clear-ticket-btn');
    const input = document.getElementById('ticket-search');

    clearBtn.classList.add('hidden');
    input.value = '';

    // Disable buttons
    document.getElementById('timer-start-btn').disabled = true;
    document.getElementById('manual-submit-btn').disabled = true;
}

async function loadAssignedTickets() {
    try {
        const tickets = await App.GetMyTickets();
        assignedTickets = tickets || [];
    } catch (err) {
        assignedTickets = [];
        console.error('Failed to load assigned tickets:', err);
    }
}

async function loadProjects(selectedProjectID = '') {
    const select = document.getElementById('project-select');
    if (!select) return;

    const previousSelection = selectedProjectID || select.value || '';
    select.innerHTML = '<option value="">— No project —</option>';

    try {
        const projects = await App.GetProjects();
        if (!projects || projects.length === 0) {
            syncTrayProjectOptions();
            return;
        }

        projects.forEach(p => {
            const opt = document.createElement('option');
            opt.value = p.id;
            opt.textContent = p.clientName ? `${p.name} (${p.clientName})` : p.name;
            select.appendChild(opt);
        });

        if (previousSelection && [...select.options].some(o => o.value === previousSelection)) {
            select.value = previousSelection;
        }
    } catch (err) {
        console.error('Failed to load projects:', err);
    } finally {
        syncTrayProjectOptions();
    }
}

// ===== Timer =====
function initTimer() {
    document.getElementById('timer-start-btn').addEventListener('click', startTimer);
    document.getElementById('timer-stop-btn').addEventListener('click', stopTimer);
    document.getElementById('timer-cancel-btn').addEventListener('click', cancelTimer);
}

async function startTimer() {
    if (!selectedTicket) {
        showToast('Please select a ticket first', 'error');
        return;
    }

    try {
        const projectId = document.getElementById('project-select').value || '';
        const description = document.getElementById('ticket-search').value.trim();
        const state = await App.StartTimer(selectedTicket.key, projectId, description);
        timerStartTime = new Date(state.startedAt);
        showTimerRunning(selectedTicket.key, selectedTicket.summary);
        showToast(`Timer started for ${selectedTicket.key}`, 'success');
    } catch (err) {
        showToast('Failed to start timer: ' + err, 'error');
    }
}

async function stopTimer() {
    try {
        const entry = await App.StopTimer();
        clearTimerUI();
        showToast(`Timer stopped — ${formatDuration(entry.duration)} logged`, 'success');
        refreshHistory();
    } catch (err) {
        const message = String(err || '');
        if (message.includes('no timer is running')) {
            clearTimerUI();
            await checkTimerStatus();
            await refreshHistory();
            showToast('Timer was already stopped. Status refreshed.', 'info');
            return;
        }
        showToast('Failed to stop timer: ' + err, 'error');
    }
}

async function cancelTimer() {
    try {
        await App.CancelTimer();
        clearTimerUI();
        showToast('Timer canceled — entry discarded', 'info');
        refreshHistory();
    } catch (err) {
        const message = String(err || '');
        if (message.includes('no timer is running')) {
            clearTimerUI();
            await checkTimerStatus();
            showToast('No running timer to cancel.', 'info');
            return;
        }
        showToast('Failed to cancel timer: ' + err, 'error');
    }
}

function showTimerRunning(ticketKey, summary) {
    document.getElementById('timer-start-btn').classList.add('hidden');
    document.getElementById('timer-stop-btn').classList.remove('hidden');
    document.getElementById('timer-cancel-btn').classList.remove('hidden');

    // In the new layout, we don't have a specific label for the ticket next to the timer, 
    // it's handled by the global ticket selector. We just update the status label.
    const statusLabel = document.getElementById('timer-status-label');
    if (statusLabel) statusLabel.textContent = 'RUNNING';

    document.getElementById('timer-display').classList.add('running');

    // Start live counter
    timerInterval = setInterval(() => {
        const elapsed = Math.floor((Date.now() - timerStartTime.getTime()) / 1000);
        document.getElementById('timer-display').textContent = formatTime(elapsed);
    }, 1000);
}

function clearTimerUI() {
    document.getElementById('timer-start-btn').classList.remove('hidden');
    document.getElementById('timer-stop-btn').classList.add('hidden');
    document.getElementById('timer-cancel-btn').classList.add('hidden');

    const statusLabel = document.getElementById('timer-status-label');
    if (statusLabel) statusLabel.textContent = 'IDLE';

    document.getElementById('timer-display').textContent = '00:00:00';
    document.getElementById('timer-display').classList.remove('running');

    if (timerInterval) {
        clearInterval(timerInterval);
        timerInterval = null;
    }
    timerStartTime = null;
}

async function checkTimerStatus() {
    try {
        const status = await App.GetTimerStatus();
        if (status && status.running) {
            timerStartTime = new Date(status.startedAt);
            selectedTicket = { key: status.ticketKey, summary: status.ticketSummary };
            selectTicket(selectedTicket);
            showTimerRunning(status.ticketKey, status.ticketSummary);
        } else {
            clearTimerUI();
        }
    } catch (err) {
        console.error('Failed to check timer status:', err);
    }
}

function initManualEntry() {
    document.getElementById('manual-submit-btn').addEventListener('click', async (e) => {
        e.preventDefault();

        if (!selectedTicket) {
            showToast('Please select a ticket first', 'error');
            return;
        }

        const req = {
            ticketKey: selectedTicket.key,
            date: document.getElementById('manual-date').value,
            startTime: document.getElementById('manual-start').value,
            endTime: document.getElementById('manual-end').value,
            description: document.getElementById('ticket-search').value.trim(),
            projectId: document.getElementById('project-select').value || '',
        };

        if (!req.date || !req.startTime || !req.endTime) {
            showToast('Please fill in all time fields', 'error');
            return;
        }

        try {
            const entry = await App.AddManualEntry(req);
            showToast(`Entry added — ${formatDuration(entry.duration)}`, 'success');
            setDefaultDates();
            refreshHistory();
        } catch (err) {
            showToast('Failed to add entry: ' + err, 'error');
        }
    });
}

function setDefaultDates() {
    const today = new Date().toISOString().split('T')[0];
    document.getElementById('manual-date').value = today;

    // History date range: last 7 days
    const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
    document.getElementById('history-start').value = weekAgo;
    document.getElementById('history-end').value = today;

    // Auto-fetch history for the default range
    fetchHistoryFromClockify();
}

// ===== History =====
function initHistory() {
    document.getElementById('history-fetch-btn').addEventListener('click', fetchHistoryFromClockify);
    // Auto-fetch when date range changes
    document.getElementById('history-start').addEventListener('change', fetchHistoryFromClockify);
    document.getElementById('history-end').addEventListener('change', fetchHistoryFromClockify);
}

async function refreshHistory() {
    try {
        const entries = await App.GetHistory();
        renderHistory(entries);
    } catch (err) {
        console.error('Failed to refresh history:', err);
    }
}

async function fetchHistoryFromClockify() {
    const start = document.getElementById('history-start').value;
    const end = document.getElementById('history-end').value;

    if (!start || !end) {
        showToast('Please select a date range', 'error');
        return;
    }

    try {
        const entries = await App.GetHistoryFromClockify(start, end);
        renderHistory(entries);
        showToast(`Fetched ${entries?.length || 0} entries from Clockify`, 'info');
    } catch (err) {
        showToast('Failed to fetch history: ' + err, 'error');
    }
}

function renderHistory(entries) {
    const container = document.getElementById('history-list');

    if (!entries || entries.length === 0) {
        container.innerHTML = `
            <div class="empty-state">
                <span class="empty-icon">📭</span>
                <p>No entries yet. Start a timer or add a manual entry.</p>
            </div>
        `;
        return;
    }

    container.innerHTML = entries.map(e => {
        const startStr = new Date(e.start).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
        const endStr = e.end ? new Date(e.end).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—';
        const dateStr = new Date(e.start).toLocaleDateString([], { month: 'short', day: 'numeric' });
        const fullSummary = String(e.ticketSummary || e.description || '').trim();
        const escapedFullSummary = escapeHtml(fullSummary);

        return `
            <div class="history-entry" data-id="${e.id}">
                <span class="entry-ticket">${e.ticketKey || '—'}</span>
                <div class="entry-details">
                    <span class="entry-description" title="${escapedFullSummary}">${escapedFullSummary}</span>
                    <span class="entry-time">${dateStr} · ${startStr} → ${endStr}</span>
                </div>
                <span class="entry-duration">${formatDuration(e.duration)}</span>
                <div class="entry-actions">
                    <button class="icon-btn edit-btn" title="Edit" data-entry='${JSON.stringify(e).replace(/'/g, "&#39;")}'>✏️</button>
                    <button class="icon-btn delete-btn" title="Delete" data-id="${e.id}">🗑️</button>
                </div>
            </div>
        `;
    }).join('');

    // Edit buttons
    container.querySelectorAll('.edit-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            const entry = JSON.parse(btn.dataset.entry);
            openEditModal(entry);
        });
    });

    // Delete buttons — use inline confirmation instead of confirm() which doesn't work in Wails WebView
    container.querySelectorAll('.delete-btn').forEach(btn => {
        btn.addEventListener('click', async () => {
            if (btn.dataset.confirming === 'true') return;

            if (!btn.dataset.confirmed) {
                btn.dataset.confirming = 'true';
                const original = btn.innerHTML;
                btn.innerHTML = '❌';
                btn.title = 'Click again to confirm';
                btn.classList.add('confirm-delete');

                const timeout = setTimeout(() => {
                    btn.innerHTML = original;
                    btn.title = 'Delete';
                    btn.classList.remove('confirm-delete');
                    delete btn.dataset.confirmed;
                    delete btn.dataset.confirming;
                }, 3000);

                btn.dataset.confirmed = 'true';
                delete btn.dataset.confirming;

                btn.addEventListener('click', async function confirmHandler() {
                    btn.removeEventListener('click', confirmHandler);
                    clearTimeout(timeout);
                    const id = btn.dataset.id;
                    try {
                        await App.DeleteEntry(id);
                        showToast('Entry deleted', 'success');
                        refreshHistory();
                    } catch (err) {
                        showToast('Failed to delete: ' + err, 'error');
                    }
                }, { once: true });
                return;
            }
        });
    });
}

// ===== Edit Modal =====
function initModal() {
    document.getElementById('edit-cancel-btn').addEventListener('click', closeEditModal);
    document.querySelector('#edit-modal .modal-backdrop')?.addEventListener('click', closeEditModal);

    document.getElementById('edit-form').addEventListener('submit', async (e) => {
        e.preventDefault();

        const req = {
            id: document.getElementById('edit-id').value,
            ticketKey: document.getElementById('edit-ticket').value.trim(),
            start: new Date(document.getElementById('edit-start').value).toISOString(),
            end: new Date(document.getElementById('edit-end').value).toISOString(),
            description: document.getElementById('edit-description').value.trim(),
        };

        try {
            await App.UpdateEntry(req);
            showToast('Entry updated', 'success');
            closeEditModal();
            refreshHistory();
        } catch (err) {
            showToast('Failed to update: ' + err, 'error');
        }
    });
}

function openEditModal(entry) {
    document.getElementById('edit-id').value = entry.id;
    document.getElementById('edit-ticket').value = entry.ticketKey || '';
    document.getElementById('edit-description').value = entry.description || entry.ticketSummary || '';

    // Format for datetime-local input
    if (entry.start) {
        const start = new Date(entry.start);
        document.getElementById('edit-start').value = formatDatetimeLocal(start);
    }
    if (entry.end) {
        const end = new Date(entry.end);
        document.getElementById('edit-end').value = formatDatetimeLocal(end);
    }

    document.getElementById('edit-modal').classList.remove('hidden');
}

function closeEditModal() {
    document.getElementById('edit-modal').classList.add('hidden');
}

function syncTrayProjectOptions() {
    const source = document.getElementById('project-select');
    const target = document.getElementById('tray-project-select');
    if (!source || !target) return;

    const previousSelection = target.value || '';
    target.innerHTML = source.innerHTML;
    if (previousSelection && [...target.options].some(o => o.value === previousSelection)) {
        target.value = previousSelection;
    }
}

function initTrayStartTimerModal() {
    const modal = document.getElementById('tray-start-modal');
    const form = document.getElementById('tray-start-form');
    const input = document.getElementById('tray-ticket-search');
    const results = document.getElementById('tray-ticket-results');
    const cancelBtn = document.getElementById('tray-start-cancel-btn');
    const backdrop = document.querySelector('#tray-start-modal .modal-backdrop');
    if (!modal || !form || !input || !results || !cancelBtn || !backdrop) return;

    cancelBtn.addEventListener('click', closeTrayStartTimerModal);
    backdrop.addEventListener('click', closeTrayStartTimerModal);
    form.addEventListener('submit', async (e) => {
        e.preventDefault();
        await startTimerFromTrayModal();
    });

    input.addEventListener('input', () => {
        clearTimeout(traySearchTimeout);
        const query = input.value.trim();
        traySelectedTicket = null;

        if (query.length === 0) {
            results.classList.add('hidden');
            return;
        }

        if (query.length === 1) {
            const filtered = assignedTickets.filter(t =>
                t.key.toUpperCase().startsWith(query.toUpperCase()) ||
                t.summary.toUpperCase().startsWith(query.toUpperCase())
            );
            if (filtered.length > 0) {
                renderTrayTicketDropdown(filtered);
            }
        }

        traySearchTimeout = setTimeout(async () => {
            try {
                const tickets = await App.SearchTickets(query);
                renderTrayTicketDropdown(tickets || []);
            } catch (err) {
                showToast('Tray ticket search failed: ' + err, 'error');
            }
        }, 250);
    });

    input.addEventListener('focus', () => {
        if (input.value.trim().length < 2 && assignedTickets.length > 0) {
            renderTrayTicketDropdown(assignedTickets);
        }
    });

    document.addEventListener('click', (e) => {
        if (modal.classList.contains('hidden')) return;
        if (!e.target.closest('#tray-start-modal .search-container')) {
            results.classList.add('hidden');
        }
    });

    if (wailsRuntime?.EventsOn) {
        wailsRuntime.EventsOn('tray-start-timer', openTrayStartTimerModal);
    }
}

function renderTrayTicketDropdown(tickets) {
    const results = document.getElementById('tray-ticket-results');
    if (!results) return;

    if (!tickets || tickets.length === 0) {
        results.innerHTML = '<div class="dropdown-item"><span class="ticket-summary">No tickets found</span></div>';
        results.classList.remove('hidden');
        return;
    }

    const shown = tickets.slice(0, 6);
    results.innerHTML = shown.map(t => {
        const fullSummary = String(t.summary || '').trim();
        const escapedFullSummary = escapeHtml(fullSummary);
        return `
        <div class="dropdown-item" data-key="${t.key}" data-summary="${escapedFullSummary}">
            <span class="ticket-key">${t.key}</span>
            <span class="ticket-summary" title="${escapedFullSummary}">${escapedFullSummary}</span>
            <span class="ticket-type-badge">${t.issueType || 'Task'}</span>
        </div>
    `;
    }).join('');

    results.querySelectorAll('.dropdown-item').forEach(item => {
        item.addEventListener('click', () => {
            traySelectedTicket = {
                key: item.dataset.key,
                summary: item.dataset.summary || '',
            };
            const input = document.getElementById('tray-ticket-search');
            const desc = document.getElementById('tray-description');
            if (input) input.value = `${traySelectedTicket.key} ${traySelectedTicket.summary}`.trim();
            if (desc && !desc.value.trim()) desc.value = `${traySelectedTicket.key} ${traySelectedTicket.summary}`.trim();
            results.classList.add('hidden');
        });
    });

    results.classList.remove('hidden');
}

function openTrayStartTimerModal() {
    const modal = document.getElementById('tray-start-modal');
    if (!modal) return;

    document.querySelector('.nav-tab[data-target="timer-view"]')?.click();
    syncTrayProjectOptions();

    const trayProject = document.getElementById('tray-project-select');
    const mainProject = document.getElementById('project-select');
    if (trayProject && mainProject && mainProject.value) {
        trayProject.value = mainProject.value;
    }

    const searchInput = document.getElementById('tray-ticket-search');
    const descInput = document.getElementById('tray-description');
    const results = document.getElementById('tray-ticket-results');
    if (results) results.classList.add('hidden');

    traySelectedTicket = selectedTicket ? { ...selectedTicket } : null;
    if (searchInput) {
        searchInput.value = traySelectedTicket
            ? `${traySelectedTicket.key} ${traySelectedTicket.summary || ''}`.trim()
            : '';
        setTimeout(() => searchInput.focus(), 0);
    }
    if (descInput) {
        descInput.value = traySelectedTicket
            ? `${traySelectedTicket.key} ${traySelectedTicket.summary || ''}`.trim()
            : '';
    }

    modal.classList.remove('hidden');
}

function closeTrayStartTimerModal() {
    document.getElementById('tray-start-modal')?.classList.add('hidden');
}

async function startTimerFromTrayModal() {
    if (!traySelectedTicket?.key) {
        showToast('Please select a ticket to start timer', 'error');
        return;
    }

    const projectId = document.getElementById('tray-project-select')?.value || '';
    let description = document.getElementById('tray-description')?.value.trim() || '';
    if (!description) {
        description = document.getElementById('tray-ticket-search')?.value.trim() || traySelectedTicket.key;
    }

    try {
        const state = await App.StartTimer(traySelectedTicket.key, projectId, description);
        selectedTicket = traySelectedTicket;
        selectTicket(selectedTicket);
        timerStartTime = new Date(state.startedAt);
        showTimerRunning(state.ticketKey || traySelectedTicket.key, state.ticketSummary || traySelectedTicket.summary || '');

        const mainProject = document.getElementById('project-select');
        if (mainProject) mainProject.value = projectId;

        closeTrayStartTimerModal();
        showToast(`Timer started for ${traySelectedTicket.key}`, 'success');
    } catch (err) {
        showToast('Failed to start timer: ' + err, 'error');
    }
}

// ===== Branch Detection (SSE via Wails Events) =====
function initBranchDetection() {
    // Listen for Wails runtime events
    if (window.runtime) {
        window.runtime.EventsOn('branch-detected', (detection) => {
            showBranchBanner(detection);
        });
        window.runtime.EventsOn('tray-timer-started', async (ticketKey) => {
            await checkTimerStatus();
            await refreshHistory();
            if (ticketKey) {
                showToast(`Tray timer started for ${ticketKey}`, 'success');
            }
        });
        window.runtime.EventsOn('tray-timer-stopped', async (ticketKey) => {
            await checkTimerStatus();
            await refreshHistory();
            if (ticketKey) {
                showToast(`Tray timer stopped for ${ticketKey}`, 'success');
            } else {
                showToast('Tray timer stopped', 'success');
            }
        });
        window.runtime.EventsOn('tray-timer-canceled', async (ticketKey) => {
            await checkTimerStatus();
            await refreshHistory();
            if (ticketKey) {
                showToast(`Tray timer canceled for ${ticketKey}`, 'info');
            } else {
                showToast('Tray timer canceled', 'info');
            }
        });
        window.runtime.EventsOn('tray-start-timer-error', (message) => {
            showToast(`Tray start failed: ${message}`, 'error');
        });
        window.runtime.EventsOn('tray-stop-timer-error', (message) => {
            showToast(`Tray stop failed: ${message}`, 'error');
        });
        window.runtime.EventsOn('tray-cancel-timer-error', (message) => {
            showToast(`Tray cancel failed: ${message}`, 'error');
        });
        window.runtime.EventsOn('window-visibility-changed', async (visible) => {
            if (visible) {
                await checkTimerStatus();
                await refreshHistory();
            }
        });
    }
}

function showBranchBanner(detection) {
    const banner = document.getElementById('branch-banner');
    document.getElementById('branch-ticket-key').textContent = detection.ticketKey;
    document.getElementById('branch-name').textContent = detection.branchName;
    document.getElementById('branch-ide').textContent = detection.ide;
    banner.classList.remove('hidden');

    // Track button
    document.getElementById('branch-track-btn').onclick = () => {
        selectTicket({
            key: detection.ticketKey,
            summary: '',
            status: '',
            issueType: '',
        });
        // Auto-start timer
        startTimer();
        banner.classList.add('hidden');
    };

    // Dismiss button
    document.getElementById('branch-dismiss-btn').onclick = () => {
        banner.classList.add('hidden');
    };
}

// ===== Toasts =====
function showToast(message, type = 'info') {
    const container = document.getElementById('toast-container');
    const icons = { success: '✅', error: '❌', info: 'ℹ️' };

    const toast = document.createElement('div');
    toast.className = `toast ${type}`;
    toast.innerHTML = `
        <span class="toast-icon">${icons[type] || icons.info}</span>
        <span>${escapeHtml(message)}</span>
    `;

    container.appendChild(toast);

    setTimeout(() => {
        toast.style.opacity = '0';
        toast.style.transform = 'translateX(20px)';
        toast.style.transition = 'all 0.3s ease';
        setTimeout(() => toast.remove(), 300);
    }, 4000);
}

// ===== Tabs =====
function initTabs() {
    const btns = document.querySelectorAll('.nav-tab');
    const panels = document.querySelectorAll('.main-view');

    btns.forEach(btn => {
        btn.addEventListener('click', () => {
            btns.forEach(b => b.classList.remove('active'));
            panels.forEach(p => {
                p.classList.remove('active');
                p.classList.add('hidden');
                p.style.display = 'none';
            });

            btn.classList.add('active');
            const target = document.getElementById(btn.dataset.target);
            target.classList.remove('hidden');
            target.classList.add('active');
            target.style.display = 'flex'; // Ensure flex layout for main-view
        });
    });
}

// ===== Mode Toggle (Timer vs Manual) =====
function initModeToggle() {
    const timerBtn = document.getElementById('mode-timer-btn');
    const manualBtn = document.getElementById('mode-manual-btn');

    // Containers
    const timerDisplay = document.getElementById('timer-display-container');
    const manualDisplay = document.getElementById('manual-display-container');

    // Action Buttons
    const startTrackerBtn = document.getElementById('timer-start-btn');
    const addManualBtn = document.getElementById('manual-submit-btn');

    timerBtn.addEventListener('click', () => {
        timerBtn.classList.replace('btn-ghost', 'btn-secondary');
        manualBtn.classList.replace('btn-secondary', 'btn-ghost');

        timerDisplay.classList.remove('hidden');
        manualDisplay.classList.add('hidden');

        startTrackerBtn.classList.remove('hidden');
        addManualBtn.classList.add('hidden');
    });

    manualBtn.addEventListener('click', () => {
        manualBtn.classList.replace('btn-ghost', 'btn-secondary');
        timerBtn.classList.replace('btn-secondary', 'btn-ghost');

        manualDisplay.classList.remove('hidden');
        timerDisplay.classList.add('hidden');

        addManualBtn.classList.remove('hidden');
        startTrackerBtn.classList.add('hidden');
    });
}

// ===== Settings =====

async function fetchAndPopulateWorkspaces(apiKey, selectedId) {
    const ws = document.getElementById('setting-clockify-ws');
    ws.innerHTML = '<option value="">Loading…</option>';
    try {
        const workspaces = await App.FetchWorkspaces(apiKey);
        ws.innerHTML = '';
        if (!workspaces || workspaces.length === 0) {
            ws.innerHTML = '<option value="">No workspaces found</option>';
            return;
        }
        for (const w of workspaces) {
            const opt = document.createElement('option');
            opt.value = w.id;
            opt.textContent = w.name;
            ws.appendChild(opt);
        }
        // Auto-select: saved value, or the only workspace
        if (selectedId && [...ws.options].some(o => o.value === selectedId)) {
            ws.value = selectedId;
        } else if (workspaces.length === 1) {
            ws.value = workspaces[0].id;
        }
    } catch (err) {
        ws.innerHTML = '<option value="">Failed to load workspaces</option>';
        console.error('Failed to fetch workspaces:', err);
    }
}

// Holds the latest update info so "Update Now" can use it
let pendingUpdateInfo = null;

function readUpdateVersion(info) {
    return info?.version || info?.Version || '';
}

function showUpdateBanner(info, forced = false) {
    pendingUpdateInfo = info;
    const banner = document.getElementById('update-banner');
    const text = document.getElementById('update-banner-text');
    const btn = document.getElementById('apply-update-btn');
    if (!banner || !text) return;
    const version = readUpdateVersion(info);
    if (!version) return;

    const prefix = forced ? '⚠️ Stable update required' : '🆕 Update available';
    text.textContent = `${prefix}: v${version}`;
    btn.textContent = 'Update Now';
    btn.dataset.mode = 'update';
    btn.disabled = false;
    banner.classList.remove('hidden');
}

function hideUpdateBanner() {
    pendingUpdateInfo = null;
    const banner = document.getElementById('update-banner');
    if (banner) banner.classList.add('hidden');
    const btn = document.getElementById('apply-update-btn');
    if (btn) {
        delete btn.dataset.mode;
        btn.textContent = 'Update Now';
    }
}

async function checkForUpdates() {
    const btn = document.getElementById('check-update-btn');
    if (btn) { btn.disabled = true; btn.textContent = '⏳ Checking…'; }

    try {
        if (!App.CheckForUpdates) return;
        const info = await App.CheckForUpdates();
        if (readUpdateVersion(info)) {
            showUpdateBanner(info, false);
        } else {
            hideUpdateBanner();
            showToast('You are up to date', 'success');
        }
    } catch (err) {
        console.error('Update check failed:', err);
        showToast('Update check failed: ' + (err?.message || err), 'error');
    } finally {
        if (btn) { btn.disabled = false; btn.textContent = '🔄 Check for Updates'; }
    }
}

async function applyUpdate() {
    if (!pendingUpdateInfo || !App.ApplyUpdate) return;
    const btn = document.getElementById('apply-update-btn');
    if (btn) { btn.disabled = true; btn.textContent = '⏳ Downloading…'; }

    try {
        await App.ApplyUpdate(pendingUpdateInfo);
        const version = readUpdateVersion(pendingUpdateInfo);
        showToast('Update applied — please restart the app', 'success');
        const text = document.getElementById('update-banner-text');
        if (text && version) text.textContent = '✅ Update installed — restart to use v' + version;
        if (btn) {
            btn.textContent = 'Restart';
            btn.dataset.mode = 'restart';
            btn.disabled = false;
        }
    } catch (err) {
        console.error('Apply update failed:', err);
        showToast('Update failed: ' + (err?.message || err), 'error');
        if (btn) {
            btn.textContent = 'Update Now';
            btn.dataset.mode = 'update';
            btn.disabled = false;
        }
    }
}

async function restartAfterUpdate() {
    const btn = document.getElementById('apply-update-btn');
    if (!btn) return;

    btn.disabled = true;
    btn.textContent = '⏳ Restarting…';
    try {
        if (App.RestartApplication) {
            await App.RestartApplication();
            return;
        }

        showToast('Restart is not available in this build. Please restart the app manually.', 'error');
        btn.textContent = 'Restart';
        btn.disabled = false;
    } catch (err) {
        console.error('Restart failed:', err);
        showToast('Restart failed: ' + (err?.message || err), 'error');
        btn.textContent = 'Restart';
        btn.disabled = false;
    }
}

async function handleUpdateButtonClick() {
    const btn = document.getElementById('apply-update-btn');
    if (btn?.dataset.mode === 'restart') {
        await restartAfterUpdate();
        return;
    }

    await applyUpdate();
}

async function loadUpdatePreferences() {
    if (!App.GetUpdatePreferences) return;
    try {
        const prefs = await App.GetUpdatePreferences();
        const autoEl = document.getElementById('setting-auto-update');
        const betaEl = document.getElementById('setting-beta-channel');
        const autoCheck = prefs?.autoCheck ?? prefs?.AutoCheck;
        const betaChannel = prefs?.betaChannel ?? prefs?.BetaChannel;
        if (autoEl) autoEl.checked = autoCheck !== false;
        if (betaEl) betaEl.checked = !!betaChannel;
    } catch (err) {
        console.error('Failed to load update prefs:', err);
    }
}

async function saveUpdatePreferences() {
    if (!App.SetUpdatePreferences) return;
    const autoEl = document.getElementById('setting-auto-update');
    const betaEl = document.getElementById('setting-beta-channel');
    try {
        await App.SetUpdatePreferences({
            autoCheck: autoEl?.checked ?? true,
            betaChannel: betaEl?.checked ?? false,
        });
    } catch (err) {
        console.error('Failed to save update prefs:', err);
        showToast('Failed to save update preferences', 'error');
    }
}

function initSettings() {
    // Display app version
    if (App.GetVersion) {
        App.GetVersion().then(v => {
            const el = document.getElementById('app-version');
            if (el) el.textContent = `JiraFy Clockwork v${v}`;
        }).catch(() => {});
    }

    // Ensure config file exists in persistent config dir
    if (App.EnsureConfigPersisted) {
        App.EnsureConfigPersisted().then(result => {
            if (result && result.created) {
                showToast(`No config file found — credentials saved to ${result.path}`, 'info');
            }
        }).catch(() => {});
    }

    // Populate form if backend supports getting config
    if (App.GetConfig) {
        App.GetConfig().then(cfg => {
            if (cfg) {
                document.getElementById('setting-clockify-key').value = cfg.ClockifyAPIKey || '';
                document.getElementById('setting-jira-url').value = cfg.JiraBaseURL || '';
                document.getElementById('setting-jira-email').value = cfg.JiraEmail || '';
                document.getElementById('setting-jira-token').value = cfg.JiraAPIToken || '';
                document.getElementById('setting-tray-show-timer').checked = cfg.TrayShowTimer !== false;
                document.getElementById('setting-tray-timer-format').value = cfg.TrayTimerFormat || 'hh:mm:ss';
                document.getElementById('setting-tray-timer-format').disabled = !document.getElementById('setting-tray-show-timer').checked;
                document.getElementById('setting-launch-on-startup').checked = cfg.LaunchOnStartup === true;
                summaryWordLimit = normalizeSummaryWordLimit(Number(cfg.SummaryWordLimit ?? 0));
                document.getElementById('setting-summary-word-limit').value = String(summaryWordLimit);
                document.getElementById('setting-log-rounding-min').value = String(
                    normalizeLogRoundingMin(Number(cfg.LogRoundingMin ?? 0))
                );

                // Load workspaces if API key is present
                if (cfg.ClockifyAPIKey) {
                    fetchAndPopulateWorkspaces(cfg.ClockifyAPIKey, cfg.ClockifyWorkspace);
                } else {
                    const ws = document.getElementById('setting-clockify-ws');
                    ws.innerHTML = '<option value="">— enter API key to load —</option>';
                }
            }
        }).catch(err => {
            console.error("Could not load config:", err);
        }).finally(() => {
            refreshIntegrationStatus();
        });
    } else {
        refreshIntegrationStatus();
    }

    // Auto-fetch workspaces when API key changes
    document.getElementById('setting-clockify-key').addEventListener('blur', () => {
        const apiKey = document.getElementById('setting-clockify-key').value.trim();
        if (apiKey) {
            fetchAndPopulateWorkspaces(apiKey, '');
        } else {
            const ws = document.getElementById('setting-clockify-ws');
            ws.innerHTML = '<option value="">— enter API key to load —</option>';
        }
    });
    document.getElementById('setting-tray-show-timer').addEventListener('change', (e) => {
        document.getElementById('setting-tray-timer-format').disabled = !e.target.checked;
    });

    document.getElementById('settings-api-form').addEventListener('submit', async (e) => {
        e.preventDefault();

        const wsVal = document.getElementById('setting-clockify-ws').value.trim();
        const selectedSummaryWordLimit = normalizeSummaryWordLimit(
            parseInt(document.getElementById('setting-summary-word-limit').value, 10)
        );
        const selectedLogRoundingMin = normalizeLogRoundingMin(
            parseInt(document.getElementById('setting-log-rounding-min').value, 10)
        );
        const config = {
            ClockifyAPIKey: document.getElementById('setting-clockify-key').value.trim(),
            ClockifyWorkspace: (wsVal && wsVal !== 'undefined') ? wsVal : '',
            JiraBaseURL: document.getElementById('setting-jira-url').value.trim(),
            JiraEmail: document.getElementById('setting-jira-email').value.trim(),
            JiraAPIToken: document.getElementById('setting-jira-token').value.trim(),
            TrayTimerFormat: document.getElementById('setting-tray-timer-format').value || 'hh:mm:ss',
            TrayShowTimer: document.getElementById('setting-tray-show-timer').checked,
            LaunchOnStartup: document.getElementById('setting-launch-on-startup').checked,
            SummaryWordLimit: selectedSummaryWordLimit,
            LogRoundingMin: selectedLogRoundingMin,
        };

        try {
            if (App.SaveConfig) {
                await App.SaveConfig(config);
                summaryWordLimit = selectedSummaryWordLimit;
                await loadProjects();
                await refreshHistory();
                showToast('Settings saved successfully', 'success');
            } else {
                showToast('SaveConfig not implemented in backend yet', 'info');
            }
        } catch (err) {
            showToast('Failed to save settings: ' + (err?.message || err), 'error');
        } finally {
            await refreshIntegrationStatus();
        }
    });

    // --- Update UI wiring ---
    loadUpdatePreferences();

    // Toggle handlers — save preferences on change
    document.getElementById('setting-auto-update')?.addEventListener('change', saveUpdatePreferences);
    document.getElementById('setting-beta-channel')?.addEventListener('change', saveUpdatePreferences);

    // Manual check button
    document.getElementById('check-update-btn')?.addEventListener('click', checkForUpdates);

    // Apply update button
    document.getElementById('apply-update-btn')?.addEventListener('click', handleUpdateButtonClick);

    // Listen for backend events (backup path — startup goroutine or tray trigger)
    if (wailsRuntime?.EventsOn) {
        wailsRuntime.EventsOn('update-available', (info) => {
            if (readUpdateVersion(info)) showUpdateBanner(info, false);
        });
        wailsRuntime.EventsOn('update-forced', (info) => {
            if (readUpdateVersion(info)) showUpdateBanner(info, true);
        });
    }

    // Proactive check: the backend startup goroutine may fire before we register
    // listeners, so we do our own check here as the primary detection path.
    if (App.CheckForUpdates) {
        App.CheckForUpdates().then(info => {
            if (readUpdateVersion(info)) showUpdateBanner(info, false);
        }).catch(err => {
            console.error('Startup update check failed:', err);
        });
    }
}

function setIntegrationBadge(elementId, state, message = '') {
    const badge = document.getElementById(elementId);
    if (!badge) return;

    if (state === 'connected') {
        badge.textContent = 'Connected';
        badge.style.background = 'rgba(34, 197, 94, 0.15)';
        badge.style.color = 'var(--success)';
    } else if (state === 'disconnected') {
        badge.textContent = 'Disconnected';
        badge.style.background = 'rgba(239, 68, 68, 0.15)';
        badge.style.color = 'var(--danger)';
    } else {
        badge.textContent = 'Checking...';
        badge.style.background = 'rgba(156, 163, 175, 0.2)';
        badge.style.color = 'var(--text-secondary)';
    }

    if (message) {
        badge.title = message;
    } else {
        badge.removeAttribute('title');
    }
}

async function refreshIntegrationStatus() {
    setIntegrationBadge('status-clockify', 'checking');
    setIntegrationBadge('status-jira', 'checking');

    if (!App.GetIntegrationStatus) {
        const msg = 'Status checks are not available in this backend build.';
        setIntegrationBadge('status-clockify', 'disconnected', msg);
        setIntegrationBadge('status-jira', 'disconnected', msg);
        return;
    }

    try {
        const status = await App.GetIntegrationStatus();
        setIntegrationBadge(
            'status-clockify',
            status.clockifyConnected ? 'connected' : 'disconnected',
            status.clockifyError || ''
        );
        setIntegrationBadge(
            'status-jira',
            status.jiraConnected ? 'connected' : 'disconnected',
            status.jiraError || ''
        );
    } catch (err) {
        const msg = err?.message || String(err);
        setIntegrationBadge('status-clockify', 'disconnected', msg);
        setIntegrationBadge('status-jira', 'disconnected', msg);
    }
}

// ===== Utility Functions =====
function escapeHtml(str) {
    if (!str) return '';
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
}
